In [1]:
import sys
import pandas as pd
sys.path.append('../')

In [2]:
# read clustering results
kmeans = pd.read_csv('../data/clustering_results/kmeans_2_results_hourly_categories_nooutliers.csv')
kmeans

,id,date,exertion_points,step_goal,minutes_below_zone_1,minutes_in_zone_1,steps,very_active_minutes,minutes_in_zone_2,minutes_in_zone_3,altitude,lightly_active_minutes,moderately_active_minutes,sedentary_minutes,exercises,exercise_duration,sleep_points,sleep_duration,calories,cluster
0,621e2e8e67b776a24055b564,2021-05-24 00:00:00,0.622928,0.0,0.936806,0.081134,0.017563,0.080685,0.000000,0.0,0.0,0.254701,0.083045,0.495139,0.074074,0.001865,0.810469,0.0,0.029382,0
1,621e2e8e67b776a24055b564,2021-05-24 01:00:00,0.622928,0.0,0.936806,0.081134,0.000000,0.080685,0.000000,0.0,0.0,0.254701,0.083045,0.495139,0.074074,0.001865,0.810469,0.0,0.002914,0
2,621e2e8e67b776a24055b564,2021-05-24 02:00:00,0.622928,0.0,0.936806,0.081134,0.046184,0.080685,0.000000,0.0,0.0,0.254701,0.083045,0.495139,0.074074,0.001865,0.810469,0.0,0.000729,0
3,621e2e8e67b776a24055b564,2021-05-24 03:00:00,0.622928,0.0,0.936806,0.081134,0.002661,0.080685,0.000000,0.0,0.0,0.254701,0.083045,0.495139,0.074074,0.001865,0.810469,0.0,0.012860,0
4,621e2e8e67b776a24055b564,2021-05-24 04:00:00,0.622928,0.0,0.936806,0.081134,0.000000,0.080685,0.000000,0.0,0.0,0.254701,0.083045,0.495139,0.074074,0.001865,0.810469,0.0,0.003315,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159778,621e375b67b776a240290cdc,2021-08-17 07:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,0.0,0.000000,0.000000,0.490278,0.000000,0.000000,0.680095,0.0,0.000383,0
159779,621e375b67b776a240290cdc,2021-08-17 08:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,0.0,0.000000,0.000000,0.490278,0.000000,0.000000,0.680095,0.0,0.000383,0
159780,621e375b67b776a240290cdc,2021-08-17 09:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,0.0,0.000000,0.000000,0.490278,0.000000,0.000000,0.680095,0.0,0.000383,0
159781,621e375b67b776a240290cdc,2021-08-17 10:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,0.0,0.000000,0.000000,0.490278,0.000000,0.000000,0.680095,0.0,0.000383,0
159782,621e375b67b776a240290cdc,2021-08-17 11:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,0.0,0.000000,0.000000,0.490278,0.000000,0.000000,0.680095,0.0,0.000383,0

In [3]:
# read the labeling data
labeling_data = pd.read_pickle('../data/preprocessing_final/labeling_df_hourly_processed.pkl')
labeling_data

,id,date,hour,ecg,heart_rate_alert,nightly_temperature,nremhr,spo2,rmssd,full_sleep_breathing_rate,...,negative_affect_score,stai_stress,ttm_stage,dramatic_relief_category,environmental_reevaluation_category,self_reevaluation_category,social_liberation_category,reinforcement_management_category,self_liberation_category,mood
0,621e2ff067b776a2403eb737,2021-12-22,19,NSR,NONE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,621e2ff067b776a2403eb737,2021-11-18,0,NaN,NaN,35.02573,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,621e2ff067b776a2403eb737,2021-11-18,21,NaN,NaN,34.866951,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,621e2ff067b776a2403eb737,2021-11-20,0,NaN,NaN,35.349583,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,621e2ff067b776a2403eb737,2021-11-20,23,NaN,NaN,34.495486,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165086,621e36f967b776a240e5e7c9,2021-05-20,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIRED
165087,621e36f967b776a240e5e7c9,2021-05-20,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RESTED/RELAXED
165088,621e36f967b776a240e5e7c9,2021-05-21,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HAPPY
165089,621e36f967b776a240e5e7c9,2021-05-21,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RESTED/RELAXED
165090,621e36f967b776a240e5e7c9,2021-05-22,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RESTED/RELAXED

In [4]:
# concatenate the date and hour columns into one datetime object column
labeling_data['date'] = pd.to_datetime(labeling_data['date']) + labeling_data['hour'] * pd.to_timedelta('1H')
labeling_data.drop(columns=['hour'], inplace=True)
labeling_data['id'] = labeling_data['id'].astype(str)
labeling_data['date'] = labeling_data['date'].astype(str)
labeling_data

,id,date,ecg,heart_rate_alert,nightly_temperature,nremhr,spo2,rmssd,full_sleep_breathing_rate,deep_sleep_breathing_rate,...,negative_affect_score,stai_stress,ttm_stage,dramatic_relief_category,environmental_reevaluation_category,self_reevaluation_category,social_liberation_category,reinforcement_management_category,self_liberation_category,mood
0,621e2ff067b776a2403eb737,2021-12-22 19:00:00,NSR,NONE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,621e2ff067b776a2403eb737,2021-11-18 00:00:00,NaN,NaN,35.02573,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,621e2ff067b776a2403eb737,2021-11-18 21:00:00,NaN,NaN,34.866951,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,621e2ff067b776a2403eb737,2021-11-20 00:00:00,NaN,NaN,35.349583,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,621e2ff067b776a2403eb737,2021-11-20 23:00:00,NaN,NaN,34.495486,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165086,621e36f967b776a240e5e7c9,2021-05-20 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIRED
165087,621e36f967b776a240e5e7c9,2021-05-20 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RESTED/RELAXED
165088,621e36f967b776a240e5e7c9,2021-05-21 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HAPPY
165089,621e36f967b776a240e5e7c9,2021-05-21 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RESTED/RELAXED
165090,621e36f967b776a240e5e7c9,2021-05-22 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RESTED/RELAXED

In [5]:
# merge the labeling features on the clustering results based on id and date and keep only the raws of the clustering results
kmeans_visualizations = kmeans.merge(labeling_data, on=['id', 'date'], how='left')
kmeans_visualizations

,id,date,exertion_points,step_goal,minutes_below_zone_1,minutes_in_zone_1,steps,very_active_minutes,minutes_in_zone_2,minutes_in_zone_3,...,negative_affect_score,stai_stress,ttm_stage,dramatic_relief_category,environmental_reevaluation_category,self_reevaluation_category,social_liberation_category,reinforcement_management_category,self_liberation_category,mood
0,621e2e8e67b776a24055b564,2021-05-24 00:00:00,0.622928,0.0,0.936806,0.081134,0.017563,0.080685,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,621e2e8e67b776a24055b564,2021-05-24 01:00:00,0.622928,0.0,0.936806,0.081134,0.000000,0.080685,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,621e2e8e67b776a24055b564,2021-05-24 02:00:00,0.622928,0.0,0.936806,0.081134,0.046184,0.080685,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,621e2e8e67b776a24055b564,2021-05-24 03:00:00,0.622928,0.0,0.936806,0.081134,0.002661,0.080685,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,621e2e8e67b776a24055b564,2021-05-24 04:00:00,0.622928,0.0,0.936806,0.081134,0.000000,0.080685,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159779,621e375b67b776a240290cdc,2021-08-17 07:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159780,621e375b67b776a240290cdc,2021-08-17 08:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159781,621e375b67b776a240290cdc,2021-08-17 09:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159782,621e375b67b776a240290cdc,2021-08-17 10:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159783,621e375b67b776a240290cdc,2021-08-17 11:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# there is one duplicate value that contains in "mood" one NaN and one 'HAPPY' value, we will keep the 'HAPPY' value, which is the last one
kmeans_visualizations = kmeans_visualizations[~kmeans_visualizations.duplicated(subset=['id', 'date'], keep='last')].reset_index(drop=True)
kmeans_visualizations.to_pickle('../data/labeling_visualizations/kmeans_categories_final_labeling.pkl')
kmeans_visualizations

,id,date,exertion_points,step_goal,minutes_below_zone_1,minutes_in_zone_1,steps,very_active_minutes,minutes_in_zone_2,minutes_in_zone_3,...,negative_affect_score,stai_stress,ttm_stage,dramatic_relief_category,environmental_reevaluation_category,self_reevaluation_category,social_liberation_category,reinforcement_management_category,self_liberation_category,mood
0,621e2e8e67b776a24055b564,2021-05-24 00:00:00,0.622928,0.0,0.936806,0.081134,0.017563,0.080685,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,621e2e8e67b776a24055b564,2021-05-24 01:00:00,0.622928,0.0,0.936806,0.081134,0.000000,0.080685,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,621e2e8e67b776a24055b564,2021-05-24 02:00:00,0.622928,0.0,0.936806,0.081134,0.046184,0.080685,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,621e2e8e67b776a24055b564,2021-05-24 03:00:00,0.622928,0.0,0.936806,0.081134,0.002661,0.080685,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,621e2e8e67b776a24055b564,2021-05-24 04:00:00,0.622928,0.0,0.936806,0.081134,0.000000,0.080685,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159778,621e375b67b776a240290cdc,2021-08-17 07:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159779,621e375b67b776a240290cdc,2021-08-17 08:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159780,621e375b67b776a240290cdc,2021-08-17 09:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159781,621e375b67b776a240290cdc,2021-08-17 10:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159782,621e375b67b776a240290cdc,2021-08-17 11:00:00,0.720932,0.0,0.736277,0.269189,0.064983,0.000000,0.024974,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN